program: experiments/singletask_baseline.py
command:
  - ${env}
  - python
  - ${program}
  - "--tokenizer"
  - bpe
  - "--experiment"
  - bpe
  - "--encoding"
  - index
  - "--model"
  - mlp
  - "--main"
  - waseem_hovy
  - "--gpu"
  - 0
  - "--patience"
  - 15
  - "--layers"
  - 1
  - "--datadir"
  - data/json/
  - "--results"
  - results/
  - "--save_model"
  - results/models/
  - "--shuffle"
  - True
  - "--cleaners"
  - username
  - hashtag
  - url
  - lower
  - "--metrics"
  - f1_score
  - accuracy
  - precision
  - recall
  - "--loss"
  - nlll
  - "--seed"
  - 42
method: bayes

metric:
  goal: maximize 
  name: dev/f1-score

parameters:
  epochs:
    values: [50, 100, 200]
  batch_size:
    values: [16, 32, 64]
  embedding:
    values: [64, 100, 200, 300]
  hidden:
    values: [64, 100, 200, 300]
  learning_rate:
    distribution: uniform
    min: 0.00001
    max: 1.0
  dropout:
    distribution: uniform
    min: 0.0
    max: 0.5
  nonlinearity:
    values: [relu, tanh]
  optimizer:
    values: [sgd, adam, asgd, adamw]
